apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eduhub-catalog-secrets
  namespace: eduhub-catalog-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv
  target:
    name: eduhub-catalog-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: redis-url
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: jwt-access-secret