apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      vaultUrl: https://teleios-eso-kv.vault.azure.net/
      authType: ManagedIdentity
