

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-acr-aksacrusw7
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv

  target:
    name: repo-acr-aksacrusw7
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: aksacrusw7.azurecr.io
        enableOCI: "true"

  data:
    - secretKey: username
      remoteRef:
        key: acr-aksacrusw7-dev-username
    - secretKey: password
      remoteRef:
        key: acr-aksacrusw7-dev-password



