apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eduhub-assignment
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: dev
            namespace: eduhub-assignment-dev
            clusterServer: https://kubernetes.default.svc
            valuesPath: applications/dev/eduhub-assignment/values.yaml
            manifestsPath: applications/dev/eduhub-assignment

  template:
    metadata:
      name: eduhub-assignment-{{ .env }}
    spec:
      project: default
      sources:
        - repoURL: aksacrusw7.azurecr.io/helm
          chart: eduhub-assignment
          targetRevision: "0.1.0"
          helm:
            valueFiles:
              - $values/{{ .valuesPath }}

        - repoURL: https://github.com/meshachdamilare/eduhub-apps-gitops.git
          targetRevision: main
          ref: values
          path: '{{ .manifestsPath }}'

      destination:
        server: '{{ .clusterServer }}'
        namespace: '{{ .namespace }}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
