apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: dev
            clusterServer: https://kubernetes.default.svc
            namespace: external-secrets-dev
            valuesFile: applications/dev/external-secret/values.yaml
  template:
    metadata:
      name: external-secrets-operator-{{ .name }}
    spec:
      project: default
      destination:
        server: '{{ .clusterServer }}'
        namespace: '{{ .namespace }}'
      source:
        repoURL: https://github.com/meshachdamilare/eduhub-apps-gitops.git  # your Git repo
        targetRevision: main
        path: charts/external-secrets                              # vendored chart path
        helm:
          valueFiles:
            - '{{ .valuesFile }}'                                 # relative path to values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
