apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: dev
            clusterServer: https://kubernetes.default.svc
            namespace: external-secrets-{{ .name }}
            valuesFile: applications/dev/external-secret/values.yaml
          # - name: prod
          #   clusterServer: https://<PROD_CLUSTER_API_SERVER>
          #   namespace: external-secrets-prod
          #   valuesFile: applications/prod/external-secret/values.yaml
  template:
    metadata:
      name: external-secrets-operator-{{ .name }}
    spec:
      project: default
      destination:
        server: '{{ .clusterServer }}'
        namespace: '{{ .namespace }}'
      source:
        repoURL: https://charts.external-secrets.io/
        chart: external-secrets
        targetRevision: "1.0.0"
        helm:
          valueFiles:
            - '{{ .valuesFile }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
