apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: dev
            clusterServer: https://kubernetes.default.svc
            namespace: external-secrets-dev
            # NOTE: path is now relative to charts/external-secrets,
            # so we go up two levels to repo root, then into applications/...
            valuesFile: ../../applications/dev/external-secret/values.yaml
  template:
    metadata:
      name: external-secrets-operator-{{ .name }}
    spec:
      project: default
      destination:
        server: '{{ .clusterServer }}'
        namespace: '{{ .namespace }}'
      source:
        repoURL: https://github.com/meshachdamilare/eduhub-apps-gitops.git
        targetRevision: main
        path: charts/external-secrets           # <- vendored chart directory
        helm:
          skipCrds: true
          valueFiles:
            - '{{ .valuesFile }}'              # <- now resolves correctly via ../../...
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
