apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: dev
            clusterServer: https://kubernetes.default.svc
            namespace: external-secrets-dev
  template:
    metadata:
      name: external-secrets-operator-{{ .name }}
    spec:
      project: default
      destination:
        server: '{{ .clusterServer }}'
        namespace: '{{ .namespace }}'
      source:
        repoURL: https://charts.external-secrets.io/
        chart: external-secrets
        targetRevision: "1.1.0"
        helm:
          values: |
            serviceAccount:
              create: true
              name: external-secrets-sa
            controller:
              resources: {}
            metrics:
              enabled: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
