
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: dev
            clusterServer:  https://kubernetes.default.svc
            namespace: external-secrets-dev
            valuesPath: applications/dev/external-secrets/values.yaml
            manifestsPath: applications/dev/external-secrets

          # - name: prod
          #   clusterServer: https://PROD_CLUSTER_API_SERVER
          #   namespace: external-secrets-prod
          #   valuesPath: applications/prod/external-secrets/values.yaml
          #   manifestsPath: applications/prod/external-secrets

  template:
    metadata:
      name: external-secrets-operator-{{ .name }}
    spec:
      project: default
      destination:
        server: '{{ .clusterServer }}'
        namespace: '{{ .namespace }}'

      source:
        - repoURL: https://charts.external-secrets.io/
          chart:  external-secrets
          targetRevision: "1.1.0"
          helm:
            valueFiles:
              - $values/{{ .valuesPath }}

        - repoURL: https://github.com/meshachdamilare/eduhub-apps-gitops.git
          targetRevision: main
          ref: values
          path: '{{ .manifestsPath }}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
