apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: dev
            clusterServer: https://kubernetes.default.svc
            namespace: logging-dev
            valuesPath: applications/dev/logging/loki-stack-values.yaml

          # Uncomment and adapt when you add prod
          # - name: prod
          #   clusterServer: https://PROD_CLUSTER_API_SERVER
          #   namespace: logging-dev
          #   valuesPath: applications/prod/logging/loki-stack-values.yaml

  template:
    metadata:
      name: loki-stack-{{ .name }}
    spec:
      project: default

      destination:
        server: '{{ .clusterServer }}'
        namespace: '{{ .namespace }}'

      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: loki-stack
          targetRevision: "2.10.2" 
          helm:
            valueFiles:
              - $values/{{ .valuesPath }}

        - repoURL: https://github.com/meshachdamilare/eduhub-apps-gitops.git
          targetRevision: main
          ref: values                      
          path: .     
              
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
